parser:
  babel-eslint

extends:
  airbnb

env:
  node: true,
  browser: true,
  es6: true

rules:
  arrow-parens:
    - error
    - always
  arrow-body-style:
    - 2
    - as-needed
  class-methods-use-this: 0
  comma-dangle:
    - 2
    - always-multiline
  semi:
    - error
    - never
  prefer-destructuring: 1
  import/imports-first: 0
  import/newline-after-import: 0
  import/no-dynamic-require: 0
  import/no-extraneous-dependencies: 0
  import/no-named-as-default: 0
  import/no-unresolved: 1
  import/no-webpack-loader-syntax: 0
  import/prefer-default-export: 0
  indent:
    - 2
    - 2
    - SwitchCase: 1
  max-len: 0
  newline-per-chained-call: 0
  no-confusing-arrow: 0
  no-console: 1
  no-use-before-define: 0
  prefer-template: 2
  require-yield: 0

parserOptions:
  ecmaVersion: 6
  sourceType: module

  ecmaFeatures:
    experimentalObjectRestSpread: true
